### ISSUE TITLE
Version 0.2.9 not compatible with Octoprint 1.5.0 

### ISSUE THREAD

**Issue by Boerner1337** [ieatacid/OctoPrint-GcodeEditor#23] opened 2020-12-03 08:41 UTC
Hey there, 

first of all: great job you did here with the plugin, I am using it on a daily basis. 
After upgrading to Octoprint 1.5.0 it seems that Version 0.2.9 of GCode Editor is not compatible anymore. 
At least I cannot see the "edit" button next to my gcode files anymore, if you find the time to fix that, I'd really appreciate it as I am using your plugin quite recently. 
That's not super suprising as these things usually happen when upgrading to a super new Octoprint version but nevertheless I just want to leave the information here for you :)

Thanks, 
Kevin

**Comment by CmdrCody51** [comment] 2020-12-03 18:47
I second this. I think this is one dam good plugin when it works. I have also used this plugin every day.
Same problem - no edit button with 1.5.0
And for Issue #4 - can't you just use the browser find-on-page?
Keep up the good work!

**Comment by sirtuxalot** [comment] 2020-12-04 16:41
Confirmed on v1.5.1 as well.  Looking forward to next update as it is a very handy tool.  Well Done!

**Comment by Whitehawk2000** [comment] 2020-12-05 10:34
I can confirm it. 
Keep up the good work!

**Comment by cmoore159** [comment] 2020-12-05 11:43
Confirmed same problem on v1.5.1 as well. Looking forward to next update as it is a very handy tool. Well Done!

**Comment by calexandre** [comment] 2020-12-05 17:26
+1 also broken for me.

**Comment by ieatacid** [comment] 2020-12-06 01:17
Should be fixed now

**Comment by CmdrCody51** [comment] 2020-12-06 05:21
Works for me.  And so does the browser find in page - Woot!

**Comment by sirtuxalot** [comment] 2020-12-06 05:40
Thank you sir, you are a gentleman and a scholar!

**Comment by Whitehawk2000** [comment] 2020-12-06 09:45
Great, after a reinstall of the plugin everything is working fine! Thank you!

**Comment by cmoore159** [comment] 2020-12-06 11:37
Thank you very much after a reinstall of the plugin everything is working fine on 1.5.1! Keep up the awesome work.

**Closed** 2020-12-06 15:30 UTC

**Comment by Boerner1337** [comment] 2020-12-06 15:34
Thank you very much! All works well now!
